#!/bin/bash
./mk_clean

assert() {
  expected="$1"
  input="$2"

  ./out.exe "$input" > out2.M1 || exit
  cat x86_defs.M1 libc-core.M1 out2.M1 > out2-0.M1
  M0 out2-0.M1 out2-0.hex2
  cat ELF-i386.hex2 out2-0.hex2 > out2-0-0.hex2
  hex2-0 out2-0-0.hex2 out2.exe
  ./out2.exe
  actual="$?"

  if [ "$actual" = "$expected" ]; then
    echo "$input => $actual"
  else
    echo "$input => $expected expected, but got $actual"
    exit 1
  fi
}

source ./tests.sh

cat bootstrap.c bootstrappable.c support_cc_x86.c support.c > ../../tmpdir/out.c

js js_to_c.js >> ../../tmpdir/out.c

cp ELF-i386.hex2 ../../tmpdir
cp libc-core.M1 ../../tmpdir
cp x86_defs.M1 ../../tmpdir

cd ../../tmpdir/

cc_x86 out.c out.M1
cat x86_defs.M1 libc-core.M1 out.M1 > out-0.M1
M0 out-0.M1 out-0.hex2
cat ELF-i386.hex2 out-0.hex2 > out-0-0.hex2
hex2-0 out-0-0.hex2 out.exe



echo "testing under cc_x86"

run_tests
